#!/usr/bin/env python3
"""Generate go/asciicharts/unicode_tables.go from Python's unicodedata, so the Go implementation measures
text exactly as the Python reference does (the same Unicode version, the same rules):

- zero width: combining marks, and general categories Mn, Me, Cf (accents, ZWJ, variation selectors);
- wide: East Asian Width W or F (CJK, most emoji);
- control: general category Cc (replaced by spaces in user text).

    python scripts/gen_go_unicode.py           # write the file
    python scripts/gen_go_unicode.py --check   # exit 1 if it is stale
"""
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "go" / "asciicharts" / "unicode_tables.go"


def ranges(pred):
    out, start, prev = [], None, None
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            ok = False
        else:
            ok = pred(chr(cp))
        if ok and start is None:
            start = cp
        if not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def table(name, rs, doc):
    lines = [f"// {doc}", f"var {name} = []runeRange{{"]
    row = []
    for lo, hi in rs:
        row.append(f"{{0x{lo:X}, 0x{hi:X}}}")
        if len(row) == 6:
            lines.append("\t" + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("\t" + ", ".join(row) + ",")
    lines.append("}")
    return "\n".join(lines)


def generate():
    zero = ranges(lambda c: bool(unicodedata.combining(c)) or unicodedata.category(c) in ("Mn", "Me", "Cf"))
    wide = ranges(lambda c: unicodedata.east_asian_width(c) in "WF")
    ctrl = ranges(lambda c: unicodedata.category(c) == "Cc")
    return "\n\n".join([
        "// Code generated by scripts/gen_go_unicode.py from Python's unicodedata "
        f"(Unicode {unicodedata.unidata_version}); DO NOT EDIT.",
        "package asciicharts",
        f"// UnicodeVersion is the Unicode version the width tables come from.\nconst UnicodeVersion = \"{unicodedata.unidata_version}\"",
        table("zeroWidthRanges", zero, "Code points that take no column: combining marks, categories Mn, Me, Cf."),
        table("wideRanges", wide, "Code points that take two columns: East Asian Width W or F."),
        table("controlRanges", ctrl, "Code points of category Cc, replaced by spaces in user text."),
    ]) + "\n"


def main(argv):
    text = generate()
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT.relative_to(ROOT)} is stale (run python scripts/gen_go_unicode.py)", file=sys.stderr)
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} (Unicode {unicodedata.unidata_version})")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
