#!/usr/bin/env python3
"""Generate go/cmd/asciicharts-mcp/tools_data.go from the Python MCP server's tools/list, so the Go
server offers the same tools with the same descriptions and JSON schemas, byte for byte.

    python scripts/gen_go_mcp_tools.py           # write the file
    python scripts/gen_go_mcp_tools.py --check   # exit 1 if it is stale

Needs the Python server's dependencies (pip install -e "./python[dev]").
"""
import asyncio
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "python"))

OUT = ROOT / "go" / "cmd" / "asciicharts-mcp" / "tools_data.go"


async def tools():
    from mcp import Client
    from asciicharts_server.app import build_server
    from asciicharts_server.store import Store

    async with Client(build_server(stats=Store())) as c:
        return [t.model_dump(mode="json", by_alias=True, exclude_none=True) for t in (await c.list_tools()).tools]


def generate():
    data = json.dumps(asyncio.run(tools()), ensure_ascii=False, indent=1)
    # one quoted Go string per line: the descriptions hold backticks, so no raw string; a JSON string
    # literal is a valid Go string literal
    lines = " +\n\t".join(json.dumps(line + "\n", ensure_ascii=False) for line in data.split("\n"))
    return ("// Code generated by scripts/gen_go_mcp_tools.py from the Python MCP server's tools/list; DO NOT EDIT.\n\n"
            "package main\n\n"
            "const toolsJSON = " + lines + "\n")


def main(argv):
    text = generate()
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT.relative_to(ROOT)} is stale (run python scripts/gen_go_mcp_tools.py)", file=sys.stderr)
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
