#!/usr/bin/env python3
"""Generate go/asciicharts/catalog_data.go from the Python reference's chart catalogue (list_charts()),
so both implementations describe the chart types with the same words and examples.

    python scripts/gen_go_catalog.py           # write the file
    python scripts/gen_go_catalog.py --check   # exit 1 if it is stale
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "python"))
from asciicharts import list_charts  # noqa: E402

OUT = ROOT / "go" / "asciicharts" / "catalog_data.go"


def generate():
    data = json.dumps(list_charts(), ensure_ascii=False, indent=1)
    return ("// Code generated by scripts/gen_go_catalog.py from the Python reference's list_charts(); DO NOT EDIT.\n\n"
            "package asciicharts\n\n"
            "const catalogJSON = `" + data + "`\n")


def main(argv):
    text = generate()
    if "`" in text[text.index("`") + 1:text.rindex("`")]:
        raise SystemExit("the catalogue contains a backtick; it can't go into a Go raw string")
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT.relative_to(ROOT)} is stale (run python scripts/gen_go_catalog.py)", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
