// Code generated by scripts/gen_go_catalog.py from the Python reference's list_charts(); DO NOT EDIT.

package asciicharts

const catalogJSON = `[
 {
  "type": "sparkline",
  "summary": "One-line trend made of block glyphs, no axes. Good inline in a sentence or log line.",
  "series": "One line per series. values: the samples in order. name (optional) is printed as a prefix.",
  "options": [],
  "example": {
   "chartType": "sparkline",
   "series": [
    {
     "name": "latency",
     "values": [
      4,
      6,
      5,
      9,
      3
     ]
    }
   ]
  }
 },
 {
  "type": "vbar",
  "summary": "Vertical bars: single, grouped or stacked. Negative values diverge from a zero baseline (stacked too).",
  "series": "values: one number per entry of labels. Several series are grouped side by side (or stacked). name is the legend entry.",
  "options": [
   "labels",
   "width",
   "height",
   "stacked",
   "style"
  ],
  "example": {
   "chartType": "vbar",
   "labels": [
    "Q1",
    "Q2",
    "Q3"
   ],
   "series": [
    {
     "name": "2025",
     "values": [
      30,
      45,
      40
     ]
    },
    {
     "name": "2026",
     "values": [
      35,
      50,
      55
     ]
    }
   ]
  }
 },
 {
  "type": "hbar",
  "summary": "Horizontal bars: single, grouped or stacked. The best choice for rankings and long labels. Negative values diverge.",
  "series": "values: one number per entry of labels. Several series are grouped (or stacked). name is the legend entry.",
  "options": [
   "labels",
   "width",
   "stacked",
   "style"
  ],
  "example": {
   "chartType": "hbar",
   "labels": [
    "Chrome",
    "Firefox",
    "Safari"
   ],
   "series": [
    {
     "values": [
      62,
      21,
      12
     ]
    }
   ]
  }
 },
 {
  "type": "line",
  "summary": "One or more lines with a value axis. Optional dashed reference lines (threshold, or several labelled thresholds) and per-point markers.",
  "series": "values: the samples in order (at least 2 per series). One line per series. labels (optional) become x-axis labels.",
  "options": [
   "labels",
   "width",
   "height",
   "style",
   "threshold",
   "thresholds",
   "showPoints",
   "pointChar"
  ],
  "example": {
   "chartType": "line",
   "series": [
    {
     "values": [
      12,
      18,
      15,
      30,
      42,
      38
     ]
    }
   ]
  }
 },
 {
  "type": "area",
  "summary": "Line series filled down to a zero baseline: overlaid or stacked. Negative values fill downward.",
  "series": "values: the samples in order (at least 2 per series, all the same length). One band per series. labels (optional) become x-axis labels.",
  "options": [
   "labels",
   "width",
   "height",
   "stacked",
   "style"
  ],
  "example": {
   "chartType": "area",
   "series": [
    {
     "values": [
      20,
      10,
      -20,
      -60,
      -120
     ]
    }
   ]
  }
 },
 {
  "type": "scatter",
  "summary": "(x, y) points only, one marker shape per series.",
  "series": "points: a list of {x, y} objects (values is not used). One marker set per series.",
  "options": [
   "width",
   "height"
  ],
  "example": {
   "chartType": "scatter",
   "series": [
    {
     "name": "A",
     "points": [
      {
       "x": 1,
       "y": 2
      },
      {
       "x": 2,
       "y": 4
      },
      {
       "x": 3,
       "y": 3
      }
     ]
    }
   ]
  }
 },
 {
  "type": "dual_axis",
  "summary": "Two lines over one x-axis, each with its own y-axis (left and right) for series on different scales.",
  "series": "Exactly two series, each with values (at least 2). The first uses the left axis, the second the right.",
  "options": [
   "width",
   "height"
  ],
  "example": {
   "chartType": "dual_axis",
   "series": [
    {
     "name": "Temp",
     "values": [
      10,
      12,
      15,
      14
     ]
    },
    {
     "name": "Humidity",
     "values": [
      80,
      78,
      65,
      70
     ]
    }
   ]
  }
 },
 {
  "type": "pie",
  "summary": "Circular pie with a legend showing each slice's value and percentage.",
  "series": "One series per slice: name is the slice label, values[0] its size (non-negative, not all zero).",
  "options": [
   "width",
   "height"
  ],
  "example": {
   "chartType": "pie",
   "series": [
    {
     "name": "Chrome",
     "values": [
      62
     ]
    },
    {
     "name": "Firefox",
     "values": [
      21
     ]
    },
    {
     "name": "Other",
     "values": [
      17
     ]
    }
   ]
  }
 },
 {
  "type": "histogram",
  "summary": "Buckets raw samples into bins and draws the counts as horizontal bars.",
  "series": "Exactly one series whose values are the raw samples (do not pre-bucket them).",
  "options": [
   "bins",
   "width",
   "style"
  ],
  "example": {
   "chartType": "histogram",
   "bins": 5,
   "series": [
    {
     "values": [
      12,
      15,
      14,
      18,
      20,
      22,
      21,
      25,
      30,
      28
     ]
    }
   ]
  }
 },
 {
  "type": "heatmap",
  "summary": "A 2-D matrix as shaded cells (or a blue-to-red color ramp with useColor).",
  "series": "One series per matrix row: name is the row label, values the cells. labels are the column headers.",
  "options": [
   "labels",
   "width"
  ],
  "example": {
   "chartType": "heatmap",
   "labels": [
    "Mon",
    "Tue",
    "Wed"
   ],
   "series": [
    {
     "name": "9am",
     "values": [
      20,
      35,
      25
     ]
    },
    {
     "name": "5pm",
     "values": [
      80,
      70,
      90
     ]
    }
   ]
  }
 },
 {
  "type": "boxplot",
  "summary": "Box-and-whisker per group (min, Q1, median, Q3, max), computed for you from the raw samples.",
  "series": "One series per group: name is the group label, values are the raw samples (not quartiles).",
  "options": [
   "width"
  ],
  "example": {
   "chartType": "boxplot",
   "series": [
    {
     "name": "Class A",
     "values": [
      55,
      60,
      62,
      65,
      70,
      72,
      75,
      80
     ]
    }
   ]
  }
 },
 {
  "type": "dotplot",
  "summary": "Cleveland dot plot: one row per category with a marker per series on a shared, zoomed value axis (does not start at 0).",
  "series": "values: one number per entry of labels. Several series put one marker each on the same row. name is the legend entry.",
  "options": [
   "labels",
   "width"
  ],
  "example": {
   "chartType": "dotplot",
   "labels": [
    "Oakland",
    "Seattle",
    "Denver"
   ],
   "series": [
    {
     "values": [
      5.2,
      4.4,
      3.6
     ]
    }
   ]
  }
 }
]`
