package asciicharts

// The conformance suite of asciicharts principles v1.3 (test/conformance/), byte for byte.

import (
	"bytes"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

var conformanceDir = filepath.Join("..", "..", "test", "conformance")

func decodeFile(t *testing.T, name string, v any) {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(conformanceDir, name))
	if err != nil {
		t.Fatal(err)
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.UseNumber()
	if err := dec.Decode(v); err != nil {
		t.Fatal(err)
	}
}

func TestCorpus(t *testing.T) {
	var corpus []map[string]any
	decodeFile(t, "corpus.json", &corpus)
	failed := 0
	for i, c := range corpus {
		out, err := Render(c["spec"])
		if want, isErr := c["err"].(string); isErr {
			var ce *ChartError
			if err == nil || !errors.As(err, &ce) || err.Error() != want {
				failed++
				t.Errorf("case %d: want error %q, got %q (err %v)", i, want, out, err)
			}
			continue
		}
		want := c["out"].(string)
		if err != nil {
			failed++
			t.Errorf("case %d: unexpected error %v", i, err)
			continue
		}
		if out != want {
			failed++
			if failed <= 5 {
				t.Errorf("case %d (%v): output differs\n--- want\n%s\n--- got\n%s", i, c["spec"].(map[string]any)["chartType"], want, out)
			} else {
				t.Errorf("case %d (%v): output differs", i, c["spec"].(map[string]any)["chartType"])
			}
		}
	}
	t.Logf("%d of %d cases conform", len(corpus)-failed, len(corpus))
}

func TestGallery(t *testing.T) {
	var gallery []struct {
		Name string         `json:"name"`
		Spec map[string]any `json:"spec"`
	}
	decodeFile(t, "gallery.json", &gallery)
	var b strings.Builder
	for _, g := range gallery {
		out, err := Render(g.Spec)
		if err != nil {
			t.Fatalf("%s: %v", g.Name, err)
		}
		b.WriteString("=== " + g.Name + " ===\n" + out + "\n\n")
	}
	want, err := os.ReadFile(filepath.Join(conformanceDir, "gallery.txt"))
	if err != nil {
		t.Fatal(err)
	}
	if b.String() != string(want) {
		got, wantLines := strings.Split(b.String(), "\n"), strings.Split(string(want), "\n")
		for i := range wantLines {
			if i >= len(got) || got[i] != wantLines[i] {
				t.Fatalf("gallery.txt differs at line %d:\nwant %q\ngot  %q", i+1, wantLines[i], got[min(i, len(got)-1)])
			}
		}
		t.Fatal("gallery.txt differs")
	}
}

func TestCurated(t *testing.T) {
	var curated []map[string]any
	decodeFile(t, "curated.json", &curated)
	for _, c := range curated {
		name := c["name"].(string)
		out, err := Render(c["spec"])
		if want, isErr := c["err"].(string); isErr {
			if err == nil || err.Error() != want {
				t.Errorf("%s: want error %q, got %q (err %v)", name, want, out, err)
			}
			continue
		}
		if err != nil {
			t.Errorf("%s: unexpected error %v", name, err)
			continue
		}
		if want := c["out"].(string); out != want {
			t.Errorf("%s: output differs\n--- want\n%s\n--- got\n%s", name, want, out)
		}
	}
	t.Logf("%d curated cases", len(curated))
}

// TestDifferential compares with the Python reference on random specs generated by
// test/parity/differential.py; it runs only when that script passes it a file.
func TestDifferential(t *testing.T) {
	path := os.Getenv("ASCIICHARTS_DIFF_FILE")
	if path == "" {
		t.Skip("set by test/parity/differential.py")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var cases []map[string]any
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.UseNumber()
	if err := dec.Decode(&cases); err != nil {
		t.Fatal(err)
	}
	failed := 0
	for i, c := range cases {
		out, err := Render(c["spec"])
		got := out
		if err != nil {
			got = "ERROR: " + err.Error()
		}
		want, _ := c["out"].(string)
		if e, isErr := c["err"].(string); isErr {
			want = "ERROR: " + e
		}
		if got != want {
			failed++
			if failed <= 5 {
				spec, _ := json.Marshal(c["spec"])
				t.Errorf("case %d differs\nspec %s\n--- python\n%s\n--- go\n%s", i, spec, want, got)
			}
		}
	}
	t.Logf("%d of %d random specs agree", len(cases)-failed, len(cases))
}

// PrinciplesVersion must name the version the principles themselves carry in their title.
func TestPrinciplesVersionMatchesTheDocument(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("..", "..", "docs", "spec", "principles.md"))
	if err != nil {
		t.Fatal(err)
	}
	title, _, _ := strings.Cut(string(data), "\n")
	if want := "# asciicharts principles v" + PrinciplesVersion; title != want {
		t.Errorf("principles.md starts %q, want %q", title, want)
	}
}
