package asciicharts

import (
	"encoding/json"
	"os"
	"testing"
)

// TestCSVDifferential compares SpecFromCSV with the Python reference's spec_from_csv on random CSV
// files generated by test/parity/differential_csv.py; it runs only when that script passes it a file.
func TestCSVDifferential(t *testing.T) {
	path := os.Getenv("ASCIICHARTS_CSV_DIFF_FILE")
	if path == "" {
		t.Skip("set by test/parity/differential_csv.py")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var cases []struct {
		CSV  string `json:"csv"`
		Args struct {
			Chart, Label, Values, Sort string
			Limit                      *int
			Set                        []string
		} `json:"args"`
		Spec, Out, Err, RenderErr string
	}
	if err := json.Unmarshal(data, &cases); err != nil {
		t.Fatal(err)
	}
	failed := 0
	for i, c := range cases {
		var got, want string
		switch {
		case c.Err != "":
			want = "ERROR: " + c.Err
		case c.RenderErr != "":
			want = c.Spec + "\nRENDER ERROR: " + c.RenderErr
		default:
			want = c.Spec + "\n" + c.Out
		}
		set, err := ParseSet(c.Args.Set)
		var spec *Object
		if err == nil {
			spec, err = SpecFromCSV(c.CSV, c.Args.Chart, CSVOptions{Label: c.Args.Label, Values: c.Args.Values,
				Sort: c.Args.Sort, Limit: c.Args.Limit, Set: set})
		}
		if err != nil {
			got = "ERROR: " + err.Error()
		} else {
			out, rerr := Render(Plain(spec))
			if rerr != nil {
				got = PyJSON(spec) + "\nRENDER ERROR: " + rerr.Error()
			} else {
				got = PyJSON(spec) + "\n" + out
			}
		}
		if got != want {
			failed++
			if failed <= 5 {
				args, _ := json.Marshal(c.Args)
				t.Errorf("case %d differs\ncsv %q\nargs %s\n--- python\n%s\n--- go\n%s", i, c.CSV, args, want, got)
			}
		}
	}
	t.Logf("%d of %d random CSV files agree", len(cases)-failed, len(cases))
}
