// Code generated by scripts/gen_go_mcp_tools.py from the Python MCP server's tools/list; DO NOT EDIT.

package main

const toolsJSON = "[\n" +
	" {\n" +
	"  \"name\": \"list_charts\",\n" +
	"  \"description\": \"List every chart type this server can draw: what it draws, how to fill `series` for it, which options apply, and a minimal example call for render_chart. Call this first when you are unsure which chart fits the data or how to shape `series`.\",\n" +
	"  \"inputSchema\": {\n" +
	"   \"type\": \"object\",\n" +
	"   \"properties\": {},\n" +
	"   \"title\": \"list_chartsArguments\"\n" +
	"  },\n" +
	"  \"outputSchema\": {\n" +
	"   \"$defs\": {\n" +
	"    \"ChartInfo\": {\n" +
	"     \"properties\": {\n" +
	"      \"type\": {\n" +
	"       \"description\": \"the chartType value to pass to render_chart\",\n" +
	"       \"title\": \"Type\",\n" +
	"       \"type\": \"string\"\n" +
	"      },\n" +
	"      \"summary\": {\n" +
	"       \"description\": \"what the chart draws and when to use it\",\n" +
	"       \"title\": \"Summary\",\n" +
	"       \"type\": \"string\"\n" +
	"      },\n" +
	"      \"series\": {\n" +
	"       \"description\": \"how to fill `series` for this chart type\",\n" +
	"       \"title\": \"Series\",\n" +
	"       \"type\": \"string\"\n" +
	"      },\n" +
	"      \"options\": {\n" +
	"       \"description\": \"render_chart options that affect this chart, beyond title/border/useColor which every chart accepts\",\n" +
	"       \"items\": {\n" +
	"        \"type\": \"string\"\n" +
	"       },\n" +
	"       \"title\": \"Options\",\n" +
	"       \"type\": \"array\"\n" +
	"      },\n" +
	"      \"example\": {\n" +
	"       \"additionalProperties\": true,\n" +
	"       \"description\": \"a minimal valid render_chart call\",\n" +
	"       \"title\": \"Example\",\n" +
	"       \"type\": \"object\"\n" +
	"      }\n" +
	"     },\n" +
	"     \"required\": [\n" +
	"      \"type\",\n" +
	"      \"summary\",\n" +
	"      \"series\",\n" +
	"      \"options\",\n" +
	"      \"example\"\n" +
	"     ],\n" +
	"     \"title\": \"ChartInfo\",\n" +
	"     \"type\": \"object\"\n" +
	"    }\n" +
	"   },\n" +
	"   \"properties\": {\n" +
	"    \"result\": {\n" +
	"     \"items\": {\n" +
	"      \"$ref\": \"#/$defs/ChartInfo\"\n" +
	"     },\n" +
	"     \"title\": \"Result\",\n" +
	"     \"type\": \"array\"\n" +
	"    }\n" +
	"   },\n" +
	"   \"required\": [\n" +
	"    \"result\"\n" +
	"   ],\n" +
	"   \"title\": \"list_chartsOutput\",\n" +
	"   \"type\": \"object\"\n" +
	"  }\n" +
	" },\n" +
	" {\n" +
	"  \"name\": \"render_chart\",\n" +
	"  \"description\": \"Render numeric data as an ASCII/Unicode text chart. Supports sparkline, vbar, hbar, line, area, scatter, dual_axis, pie, histogram, heatmap, boxplot and dotplot, with an optional title, border frame (none/ascii/light/heavy/double/rounded), bar/area fill style (solid/halftone/ascii) and line style (solid/dotted), dashed reference lines (a threshold, or several labelled thresholds such as a target and an SLA) and configurable per-point markers for line charts, a target chart width (vbar/hbar scale to fill it), automatic diverging bars for negative values (including stacked), and optional ANSI 256-color output. Returns the chart as plain text — put it in a code block so it stays aligned. Use list_charts to see how `series` is filled for each chartType.\",\n" +
	"  \"inputSchema\": {\n" +
	"   \"type\": \"object\",\n" +
	"   \"$defs\": {\n" +
	"    \"Point\": {\n" +
	"     \"properties\": {\n" +
	"      \"x\": {\n" +
	"       \"title\": \"X\",\n" +
	"       \"type\": \"number\"\n" +
	"      },\n" +
	"      \"y\": {\n" +
	"       \"title\": \"Y\",\n" +
	"       \"type\": \"number\"\n" +
	"      }\n" +
	"     },\n" +
	"     \"required\": [\n" +
	"      \"x\",\n" +
	"      \"y\"\n" +
	"     ],\n" +
	"     \"title\": \"Point\",\n" +
	"     \"type\": \"object\"\n" +
	"    },\n" +
	"    \"Series\": {\n" +
	"     \"properties\": {\n" +
	"      \"name\": {\n" +
	"       \"anyOf\": [\n" +
	"        {\n" +
	"         \"type\": \"string\"\n" +
	"        },\n" +
	"        {\n" +
	"         \"type\": \"null\"\n" +
	"        }\n" +
	"       ],\n" +
	"       \"default\": null,\n" +
	"       \"description\": \"optional series/category/row name, used in legends and axis labels\",\n" +
	"       \"title\": \"Name\"\n" +
	"      },\n" +
	"      \"values\": {\n" +
	"       \"anyOf\": [\n" +
	"        {\n" +
	"         \"items\": {\n" +
	"          \"type\": \"number\"\n" +
	"         },\n" +
	"         \"type\": \"array\"\n" +
	"        },\n" +
	"        {\n" +
	"         \"type\": \"null\"\n" +
	"        }\n" +
	"       ],\n" +
	"       \"default\": null,\n" +
	"       \"description\": \"numeric values; meaning depends on chartType, see list_charts\",\n" +
	"       \"title\": \"Values\"\n" +
	"      },\n" +
	"      \"points\": {\n" +
	"       \"anyOf\": [\n" +
	"        {\n" +
	"         \"items\": {\n" +
	"          \"$ref\": \"#/$defs/Point\"\n" +
	"         },\n" +
	"         \"type\": \"array\"\n" +
	"        },\n" +
	"        {\n" +
	"         \"type\": \"null\"\n" +
	"        }\n" +
	"       ],\n" +
	"       \"default\": null,\n" +
	"       \"description\": \"(x, y) samples, used only by scatter charts\",\n" +
	"       \"title\": \"Points\"\n" +
	"      }\n" +
	"     },\n" +
	"     \"title\": \"Series\",\n" +
	"     \"type\": \"object\"\n" +
	"    },\n" +
	"    \"Threshold\": {\n" +
	"     \"properties\": {\n" +
	"      \"value\": {\n" +
	"       \"title\": \"Value\",\n" +
	"       \"type\": \"number\"\n" +
	"      },\n" +
	"      \"label\": {\n" +
	"       \"anyOf\": [\n" +
	"        {\n" +
	"         \"maxLength\": 40,\n" +
	"         \"type\": \"string\"\n" +
	"        },\n" +
	"        {\n" +
	"         \"type\": \"null\"\n" +
	"        }\n" +
	"       ],\n" +
	"       \"default\": null,\n" +
	"       \"description\": \"shown right of the plot next to the value, e.g. \\\"target\\\" or \\\"SLA\\\"\",\n" +
	"       \"title\": \"Label\"\n" +
	"      }\n" +
	"     },\n" +
	"     \"required\": [\n" +
	"      \"value\"\n" +
	"     ],\n" +
	"     \"title\": \"Threshold\",\n" +
	"     \"type\": \"object\"\n" +
	"    }\n" +
	"   },\n" +
	"   \"properties\": {\n" +
	"    \"chartType\": {\n" +
	"     \"description\": \"chart type; see list_charts\",\n" +
	"     \"enum\": [\n" +
	"      \"sparkline\",\n" +
	"      \"vbar\",\n" +
	"      \"hbar\",\n" +
	"      \"line\",\n" +
	"      \"area\",\n" +
	"      \"scatter\",\n" +
	"      \"dual_axis\",\n" +
	"      \"pie\",\n" +
	"      \"histogram\",\n" +
	"      \"heatmap\",\n" +
	"      \"boxplot\",\n" +
	"      \"dotplot\"\n" +
	"     ],\n" +
	"     \"title\": \"Charttype\",\n" +
	"     \"type\": \"string\"\n" +
	"    },\n" +
	"    \"series\": {\n" +
	"     \"description\": \"one or more data series/rows/slices to plot; see list_charts for how each chartType reads them\",\n" +
	"     \"items\": {\n" +
	"      \"$ref\": \"#/$defs/Series\"\n" +
	"     },\n" +
	"     \"title\": \"Series\",\n" +
	"     \"type\": \"array\"\n" +
	"    },\n" +
	"    \"labels\": {\n" +
	"     \"anyOf\": [\n" +
	"      {\n" +
	"       \"items\": {\n" +
	"        \"type\": \"string\"\n" +
	"       },\n" +
	"       \"type\": \"array\"\n" +
	"      },\n" +
	"      {\n" +
	"       \"type\": \"null\"\n" +
	"      }\n" +
	"     ],\n" +
	"     \"default\": null,\n" +
	"     \"description\": \"category labels for vbar/hbar/histogram/dotplot bars, x-axis labels for line/area, or column headers for a heatmap\",\n" +
	"     \"title\": \"Labels\"\n" +
	"    },\n" +
	"    \"title\": {\n" +
	"     \"anyOf\": [\n" +
	"      {\n" +
	"       \"type\": \"string\"\n" +
	"      },\n" +
	"      {\n" +
	"       \"type\": \"null\"\n" +
	"      }\n" +
	"     ],\n" +
	"     \"default\": null,\n" +
	"     \"description\": \"optional title shown above the chart\",\n" +
	"     \"title\": \"Title\"\n" +
	"    },\n" +
	"    \"width\": {\n" +
	"     \"anyOf\": [\n" +
	"      {\n" +
	"       \"maximum\": 500,\n" +
	"       \"minimum\": 0,\n" +
	"       \"type\": \"integer\"\n" +
	"      },\n" +
	"      {\n" +
	"       \"type\": \"null\"\n" +
	"      }\n" +
	"     ],\n" +
	"     \"default\": null,\n" +
	"     \"description\": \"chart width in characters (default depends on chart type)\",\n" +
	"     \"title\": \"Width\"\n" +
	"    },\n" +
	"    \"height\": {\n" +
	"     \"anyOf\": [\n" +
	"      {\n" +
	"       \"maximum\": 200,\n" +
	"       \"minimum\": 0,\n" +
	"       \"type\": \"integer\"\n" +
	"      },\n" +
	"      {\n" +
	"       \"type\": \"null\"\n" +
	"      }\n" +
	"     ],\n" +
	"     \"default\": null,\n" +
	"     \"description\": \"chart height in rows (default depends on chart type)\",\n" +
	"     \"title\": \"Height\"\n" +
	"    },\n" +
	"    \"border\": {\n" +
	"     \"anyOf\": [\n" +
	"      {\n" +
	"       \"enum\": [\n" +
	"        \"none\",\n" +
	"        \"ascii\",\n" +
	"        \"light\",\n" +
	"        \"heavy\",\n" +
	"        \"double\",\n" +
	"        \"rounded\"\n" +
	"       ],\n" +
	"       \"type\": \"string\"\n" +
	"      },\n" +
	"      {\n" +
	"       \"type\": \"null\"\n" +
	"      }\n" +
	"     ],\n" +
	"     \"default\": null,\n" +
	"     \"description\": \"border style (default: light)\",\n" +
	"     \"title\": \"Border\"\n" +
	"    },\n" +
	"    \"style\": {\n" +
	"     \"anyOf\": [\n" +
	"      {\n" +
	"       \"enum\": [\n" +
	"        \"solid\",\n" +
	"        \"fine\",\n" +
	"        \"halftone\",\n" +
	"        \"ascii\",\n" +
	"        \"dotted\"\n" +
	"       ],\n" +
	"       \"type\": \"string\"\n" +
	"      },\n" +
	"      {\n" +
	"       \"type\": \"null\"\n" +
	"      }\n" +
	"     ],\n" +
	"     \"default\": null,\n" +
	"     \"description\": \"visual style. vbar/hbar/histogram/area: solid (default; flat blocks, bars end on whole character cells), fine (bars end on eighth-block glyphs for sub-cell precision; needs a font that has them, which Consolas does not), halftone (lighter stippled Unicode shades per series) or ascii (plain-ASCII characters per series — #, X, H, W, =, :, |, . then @ % & $ M N D O U S G Z / \\\\ ! — that render identically in any monospace font). line: solid (default) or dotted (sparse plotted-dot trend line)\",\n" +
	"     \"title\": \"Style\"\n" +
	"    },\n" +
	"    \"stacked\": {\n" +
	"     \"anyOf\": [\n" +
	"      {\n" +
	"       \"type\": \"boolean\"\n" +
	"      },\n" +
	"      {\n" +
	"       \"type\": \"null\"\n" +
	"      }\n" +
	"     ],\n" +
	"     \"default\": null,\n" +
	"     \"description\": \"for vbar/hbar/area with multiple series, stack them (cumulative from zero; negative values stack the other way) instead of grouping/overlaying\",\n" +
	"     \"title\": \"Stacked\"\n" +
	"    },\n" +
	"    \"bins\": {\n" +
	"     \"anyOf\": [\n" +
	"      {\n" +
	"       \"maximum\": 500,\n" +
	"       \"minimum\": 0,\n" +
	"       \"type\": \"integer\"\n" +
	"      },\n" +
	"      {\n" +
	"       \"type\": \"null\"\n" +
	"      }\n" +
	"     ],\n" +
	"     \"default\": null,\n" +
	"     \"description\": \"number of buckets for histogram charts (default: 10)\",\n" +
	"     \"title\": \"Bins\"\n" +
	"    },\n" +
	"    \"useColor\": {\n" +
	"     \"anyOf\": [\n" +
	"      {\n" +
	"       \"enum\": [\n" +
	"        \"auto\",\n" +
	"        \"on\",\n" +
	"        \"off\"\n" +
	"       ],\n" +
	"       \"type\": \"string\"\n" +
	"      },\n" +
	"      {\n" +
	"       \"type\": \"null\"\n" +
	"      }\n" +
	"     ],\n" +
	"     \"default\": null,\n" +
	"     \"description\": \"ANSI 256-color output (default: auto, which is equivalent to off since tool output is plain text for an agent, not a terminal)\",\n" +
	"     \"title\": \"Usecolor\"\n" +
	"    },\n" +
	"    \"threshold\": {\n" +
	"     \"anyOf\": [\n" +
	"      {\n" +
	"       \"type\": \"number\"\n" +
	"      },\n" +
	"      {\n" +
	"       \"type\": \"null\"\n" +
	"      }\n" +
	"     ],\n" +
	"     \"default\": null,\n" +
	"     \"description\": \"line charts only: draw a dashed horizontal reference line at this y-value\",\n" +
	"     \"title\": \"Threshold\"\n" +
	"    },\n" +
	"    \"thresholds\": {\n" +
	"     \"anyOf\": [\n" +
	"      {\n" +
	"       \"items\": {\n" +
	"        \"$ref\": \"#/$defs/Threshold\"\n" +
	"       },\n" +
	"       \"maxItems\": 20,\n" +
	"       \"type\": \"array\"\n" +
	"      },\n" +
	"      {\n" +
	"       \"type\": \"null\"\n" +
	"      }\n" +
	"     ],\n" +
	"     \"default\": null,\n" +
	"     \"description\": \"line charts only: several dashed horizontal reference lines, each named with its value right of the plot, e.g. [{\\\"value\\\": 106, \\\"label\\\": \\\"target\\\"}]\",\n" +
	"     \"title\": \"Thresholds\"\n" +
	"    },\n" +
	"    \"showPoints\": {\n" +
	"     \"anyOf\": [\n" +
	"      {\n" +
	"       \"type\": \"boolean\"\n" +
	"      },\n" +
	"      {\n" +
	"       \"type\": \"null\"\n" +
	"      }\n" +
	"     ],\n" +
	"     \"default\": null,\n" +
	"     \"description\": \"line charts only: mark each individual data point with a glyph on top of the connecting line\",\n" +
	"     \"title\": \"Showpoints\"\n" +
	"    },\n" +
	"    \"pointChar\": {\n" +
	"     \"anyOf\": [\n" +
	"      {\n" +
	"       \"type\": \"string\"\n" +
	"      },\n" +
	"      {\n" +
	"       \"type\": \"null\"\n" +
	"      }\n" +
	"     ],\n" +
	"     \"default\": null,\n" +
	"     \"description\": \"line charts only, with showPoints: single character used to mark points on every series (default: a large circle for the first series, with a distinct shape per additional series)\",\n" +
	"     \"title\": \"Pointchar\"\n" +
	"    }\n" +
	"   },\n" +
	"   \"required\": [\n" +
	"    \"chartType\",\n" +
	"    \"series\"\n" +
	"   ],\n" +
	"   \"title\": \"render_chartArguments\"\n" +
	"  },\n" +
	"  \"outputSchema\": {\n" +
	"   \"properties\": {\n" +
	"    \"result\": {\n" +
	"     \"title\": \"Result\",\n" +
	"     \"type\": \"string\"\n" +
	"    }\n" +
	"   },\n" +
	"   \"required\": [\n" +
	"    \"result\"\n" +
	"   ],\n" +
	"   \"title\": \"render_chartOutput\",\n" +
	"   \"type\": \"object\"\n" +
	"  }\n" +
	" }\n" +
	"]\n"
